-- Seed Data for GreenNest E-Nursery
USE greennest_db;

-- Insert Categories
INSERT INTO categories (name, slug, description, icon) VALUES
('Plants', 'plants', 'Live plants for indoor and outdoor gardens', '🌿'),
('Seeds', 'seeds', 'High-quality seeds for growing your own plants', '🌱'),
('Fertilizers & Nutrients', 'fertilizers', 'Plant fertilizers and nutrient supplements', '💧'),
('Pots & Planters', 'pots-planters', 'Decorative and functional pots and planters', '🪴'),
('Garden Tools', 'garden-tools', 'Essential tools for gardening and plant care', '🔧'),
('Pesticides', 'pesticides', 'Safe and effective pest control solutions', '🛡️');

-- Insert Sample Products - Plants
INSERT INTO products (name, slug, description, short_description, category_id, price, stock_quantity, sku, image_url, status, featured, care_instructions, tags) VALUES
('Monstera Deliciosa', 'monstera-deliciosa', 'A stunning tropical plant with large, glossy leaves featuring natural holes. Perfect for adding a modern, jungle-like aesthetic to any room. Low maintenance and perfect for beginners.', 'Low maintenance tropical plant perfect for beginners.', 1, 29.99, 24, 'PLT-001', 'https://images.unsplash.com/photo-1614594975525-e45190c55d0b?auto=format&fit=crop&w=500&q=80', 'active', TRUE, 'Water when top 2 inches of soil are dry. Prefers bright, indirect light. Mist leaves weekly for humidity.', 'indoor,tropical,low-maintenance'),
('Snake Plant', 'snake-plant', 'Also known as Sansevieria, this hardy plant thrives on neglect and is perfect for low-light areas. Excellent air purifier that removes toxins from the air.', 'Hardy indoor plant that thrives on neglect.', 1, 24.99, 30, 'PLT-002', 'https://images.unsplash.com/photo-1509937528035-ad76254b0356?auto=format&fit=crop&w=500&q=80', 'active', TRUE, 'Water sparingly - once every 2-3 weeks. Can tolerate low light but prefers indirect sunlight.', 'indoor,air-purifier,low-light'),
('Blue Cactus', 'blue-cactus', 'A striking blue-tinted succulent that adds a unique pop of color to your collection. Perfect for sunny windowsills and requires minimal care.', 'Striking blue-tinted succulent for sunny spots.', 1, 19.99, 15, 'PLT-003', 'https://images.unsplash.com/photo-1628873891973-5b37f4bd7dc0?auto=format&fit=crop&w=500&q=80', 'active', TRUE, 'Water deeply but infrequently - every 2-3 weeks. Needs bright, direct sunlight. Well-draining soil essential.', 'succulent,cactus,sunny'),
('Golden Pothos', 'golden-pothos', 'A trailing vine with heart-shaped leaves featuring beautiful golden variegation. Perfect for hanging baskets or training up a trellis.', 'Trailing vine perfect for shelves and hanging baskets.', 1, 22.99, 35, 'PLT-004', 'https://images.unsplash.com/photo-1616694547884-e8c29445eef0?auto=format&fit=crop&w=500&q=80', 'active', TRUE, 'Water when soil feels dry. Thrives in bright, indirect light but can tolerate low light. Trim regularly to encourage bushiness.', 'indoor,trailing,low-light'),
('Boston Fern', 'boston-fern', 'Lush green foliage ideal for shaded areas. This classic fern adds a touch of elegance and helps purify the air in your home.', 'Lush green foliage ideal for shaded areas.', 1, 27.99, 20, 'PLT-005', 'https://images.unsplash.com/photo-1466781783364-36c955e42a7f?auto=format&fit=crop&w=500&q=80', 'active', TRUE, 'Keep soil consistently moist but not soggy. Prefers high humidity and indirect light. Mist daily in dry environments.', 'outdoor,fern,shade-loving'),
('Fiddle Leaf Fig', 'fiddle-leaf-fig', 'A statement-making indoor tree with large, violin-shaped leaves. Fiddle Leaf Figs love bright, filtered light and bring a sophisticated, modern look to your living space.', 'Statement-making indoor tree with large, violin-shaped leaves.', 1, 55.00, 12, 'PLT-006', 'https://images.unsplash.com/photo-1628873891973-5b37f4bd7dc0?auto=format&fit=crop&w=600&q=80', 'active', TRUE, 'Bright, indirect light. Water when top 2 inches are dry. Prefers 30-65% humidity. Keep between 60-75°F.', 'indoor,tree,statement-plant');

-- Insert Sample Products - Seeds
INSERT INTO products (name, slug, description, short_description, category_id, price, stock_quantity, sku, image_url, status, featured, care_instructions, tags) VALUES
('Tomato Seeds - Heirloom', 'tomato-seeds-heirloom', 'Premium heirloom tomato seeds. Produces large, juicy tomatoes perfect for salads and cooking. Non-GMO and organic.', 'Premium heirloom tomato seeds for your garden.', 2, 4.99, 150, 'SED-001', 'https://images.unsplash.com/photo-1592841200221-a6898f307baa?auto=format&fit=crop&w=500&q=80', 'active', TRUE, 'Sow indoors 6-8 weeks before last frost. Plant 1/4 inch deep. Keep soil moist. Transplant outdoors after danger of frost.', 'vegetable,heirloom,organic'),
('Sunflower Seeds Mix', 'sunflower-seeds-mix', 'Beautiful mix of colorful sunflower varieties. Easy to grow and perfect for attracting birds and bees to your garden.', 'Colorful mix of sunflower varieties.', 2, 3.99, 200, 'SED-002', 'https://images.unsplash.com/photo-1597848212624-e593beb5c0a8?auto=format&fit=crop&w=500&q=80', 'active', FALSE, 'Sow directly in ground after last frost. Plant 1 inch deep, 6 inches apart. Water regularly. Full sun required.', 'flower,outdoor,bird-friendly'),
('Basil Seeds - Sweet', 'basil-seeds-sweet', 'Classic sweet basil seeds perfect for culinary use. Fast-growing and aromatic, ideal for kitchen gardens.', 'Classic sweet basil for culinary use.', 2, 2.99, 180, 'SED-003', 'https://images.unsplash.com/photo-1618375569909-3c8616cf7733?auto=format&fit=crop&w=500&q=80', 'active', TRUE, 'Sow indoors 6-8 weeks before last frost. Keep soil warm and moist. Pinch flowers to encourage leaf growth.', 'herb,culinary,indoor');

-- Insert Sample Products - Fertilizers
INSERT INTO products (name, slug, description, short_description, category_id, price, stock_quantity, sku, image_url, status, featured, care_instructions, tags) VALUES
('Organic Plant Food - All Purpose', 'organic-plant-food', '100% organic, slow-release fertilizer suitable for all plants. Rich in nitrogen, phosphorus, and potassium. Safe for indoor and outdoor use.', 'All-purpose organic fertilizer for healthy plant growth.', 3, 12.99, 45, 'FERT-001', 'https://images.unsplash.com/photo-1614594975525-e45190c55d0b?auto=format&fit=crop&w=500&q=80', 'active', TRUE, 'Apply every 4-6 weeks during growing season. Mix with water according to package instructions. Store in cool, dry place.', 'organic,all-purpose,slow-release'),
('Liquid Fertilizer - Bloom Booster', 'liquid-fertilizer-bloom', 'High-phosphorus liquid fertilizer designed to promote abundant flowering. Perfect for flowering plants, roses, and annuals.', 'Promotes abundant flowering in plants.', 3, 9.99, 60, 'FERT-002', 'https://images.unsplash.com/photo-1614594975525-e45190c55d0b?auto=format&fit=crop&w=500&q=80', 'active', FALSE, 'Apply every 2 weeks during blooming season. Dilute according to instructions. Water plants before applying.', 'flowering,phosphorus,liquid'),
('Cactus & Succulent Food', 'cactus-succulent-food', 'Specially formulated fertilizer for cacti and succulents. Low nitrogen content prevents overgrowth while providing essential nutrients.', 'Specialized fertilizer for cacti and succulents.', 3, 8.99, 50, 'FERT-003', 'https://images.unsplash.com/photo-1614594975525-e45190c55d0b?auto=format&fit=crop&w=500&q=80', 'active', TRUE, 'Apply monthly during growing season (spring-summer). Reduce to every 2-3 months in fall/winter. Use sparingly.', 'cactus,succulent,low-nitrogen');

-- Insert Sample Products - Pots & Planters
INSERT INTO products (name, slug, description, short_description, category_id, price, stock_quantity, sku, image_url, status, featured, care_instructions, tags) VALUES
('Ceramic Planter - 8 inch', 'ceramic-planter-8inch', 'Beautiful glazed ceramic planter with drainage hole. Available in multiple colors. Perfect for medium-sized plants.', 'Elegant ceramic planter with drainage.', 4, 18.99, 40, 'POT-001', 'https://images.unsplash.com/photo-1485955900006-10f4d324d411?auto=format&fit=crop&w=500&q=80', 'active', TRUE, 'Includes drainage hole. Place saucer underneath to catch excess water. Suitable for indoor and outdoor use.', 'ceramic,drainage,medium'),
('Hanging Basket - Macrame', 'hanging-basket-macrame', 'Stylish macrame hanger with coconut coir liner. Perfect for trailing plants like pothos, ivy, or ferns. Adjustable length.', 'Macrame hanger for trailing plants.', 4, 24.99, 25, 'POT-002', 'https://images.unsplash.com/photo-1519336056116-9e466eccad0a?auto=format&fit=crop&w=500&q=80', 'active', TRUE, 'Soak coconut liner before planting. Water regularly as hanging plants dry out faster. Adjust height as needed.', 'hanging,macrame,trailing'),
('Self-Watering Planter - 10 inch', 'self-watering-planter', 'Innovative self-watering planter with built-in water reservoir. Reduces watering frequency and prevents overwatering.', 'Self-watering planter with water reservoir.', 4, 32.99, 30, 'POT-003', 'https://images.unsplash.com/photo-1485955900006-10f4d324d411?auto=format&fit=crop&w=500&q=80', 'active', TRUE, 'Fill water reservoir through side opening. Check water level indicator weekly. Refill when indicator shows low.', 'self-watering,reservoir,low-maintenance');

-- Insert Sample Products - Garden Tools
INSERT INTO products (name, slug, description, short_description, category_id, price, stock_quantity, sku, image_url, status, featured, care_instructions, tags) VALUES
('Pruning Shears - Professional', 'pruning-shears-professional', 'Heavy-duty pruning shears with ergonomic handles. Sharp stainless steel blades perfect for trimming branches and stems.', 'Professional-grade pruning shears.', 5, 24.99, 35, 'TOOL-001', 'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?auto=format&fit=crop&w=500&q=80', 'active', TRUE, 'Clean blades after each use. Oil joints regularly. Store in dry place. Sharp blades - handle with care.', 'pruning,shears,professional'),
('Watering Can - 2 Gallon', 'watering-can-2gallon', 'Durable plastic watering can with detachable rose for gentle watering. Large capacity perfect for outdoor gardens.', 'Large capacity watering can with rose attachment.', 5, 19.99, 50, 'TOOL-002', 'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?auto=format&fit=crop&w=500&q=80', 'active', TRUE, 'Detach rose for direct watering. Clean regularly to prevent algae buildup. Store empty and dry.', 'watering,outdoor,large-capacity'),
('Garden Trowel Set - 3 Piece', 'garden-trowel-set', 'Complete set of stainless steel garden trowels in three sizes. Essential tools for planting, transplanting, and soil work.', 'Three-piece stainless steel trowel set.', 5, 16.99, 60, 'TOOL-003', 'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?auto=format&fit=crop&w=500&q=80', 'active', TRUE, 'Clean after each use. Store in dry place. Hand wash only. Stainless steel resists rust.', 'trowel,planting,set');

-- Insert Sample Products - Pesticides
INSERT INTO products (name, slug, description, short_description, category_id, price, stock_quantity, sku, image_url, status, featured, care_instructions, tags) VALUES
('Neem Oil - Organic Pest Control', 'neem-oil-organic', '100% organic neem oil spray effective against aphids, mites, and other common garden pests. Safe for plants and beneficial insects.', 'Organic neem oil for safe pest control.', 6, 14.99, 40, 'PEST-001', 'https://images.unsplash.com/photo-1614594975525-e45190c55d0b?auto=format&fit=crop&w=500&q=80', 'active', TRUE, 'Shake well before use. Spray on affected plants, covering both sides of leaves. Apply in early morning or evening. Repeat weekly if needed.', 'organic,neem-oil,safe'),
('Insecticidal Soap Spray', 'insecticidal-soap-spray', 'Ready-to-use insecticidal soap that kills soft-bodied insects on contact. Safe for vegetables, fruits, and ornamental plants.', 'Ready-to-use soap spray for soft-bodied insects.', 6, 11.99, 55, 'PEST-002', 'https://images.unsplash.com/photo-1614594975525-e45190c55d0b?auto=format&fit=crop&w=500&q=80', 'active', FALSE, 'Spray directly on pests. Apply to both sides of leaves. Use in cool weather to avoid leaf burn. Safe for edible plants.', 'soap,ready-to-use,vegetables'),
('Fungicide - Copper Based', 'fungicide-copper', 'Copper-based fungicide effective against common plant diseases like powdery mildew, blight, and leaf spot. Organic approved.', 'Copper-based fungicide for plant diseases.', 6, 13.99, 30, 'PEST-003', 'https://images.unsplash.com/photo-1614594975525-e45190c55d0b?auto=format&fit=crop&w=500&q=80', 'active', TRUE, 'Mix according to instructions. Apply preventatively or at first sign of disease. Do not apply in hot weather. Follow label directions.', 'fungicide,copper,organic-approved');
